<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <LangVersion>latest</LangVersion>
        <Description>Town Of Us Mira</Description>
        <RootNamespace>TownOfUs</RootNamespace>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <Version>1.1.2</Version>
    </PropertyGroup>

    <ItemGroup>
        <EmbeddedResource Include="Resources\**\*.*" />
    </ItemGroup>

    <Import Project="../AmongUs.props" />

</Project>